"""
train_mini_deepseek.py
=======================
Step 2 + 3 of Sir's roadmap: Data Pipeline + Training Loop.

Trains CustomMiniDeepSeek on the real log files generated by generate_logs.py
and generate_3_log_files.py using a standard PyTorch Causal LM training loop.

The model learns to predict the next token in log sequences — the same
objective used to pretrain GPT, LLaMA, and DeepSeek.

Run:
    python3 train_mini_deepseek.py                  # CPU (slow but works)
    python3 train_mini_deepseek.py --epochs 10      # more epochs
    python3 train_mini_deepseek.py --device cuda    # GPU (fast)

Output:
    ./my_custom_mini_deepseek/
        ├── model.safetensors    ← trained weights
        ├── config.json          ← architecture config
        └── tokenizer files      ← GPT-2 tokenizer (for vLLM)
"""

import os
import glob
import argparse
import time

import torch
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

from transformers import AutoTokenizer
from mini_deepseek_model import CustomMiniDeepSeek, MiniDeepSeekConfig


# ─────────────────────────────────────────────────────────────────────────────
# 1. Dataset — reads all real log files
# ─────────────────────────────────────────────────────────────────────────────

class LogDataset(Dataset):
    """
    Reads every .log file in the logs/ directory.
    Tokenises each line and creates fixed-length chunks of `max_length` tokens.
    For Causal LM, labels = input_ids (the model predicts its own input shifted by 1).
    """

    def __init__(self, tokenizer, max_length: int = 128, log_dir: str = "logs"):
        self.examples  = []
        self.max_length = max_length

        log_files = glob.glob(os.path.join(log_dir, "*.log"))
        if not log_files:
            raise FileNotFoundError(
                f"No .log files found in {log_dir}/\n"
                f"Run: python3 generate_logs.py && python3 generate_3_log_files.py"
            )

        all_text = ""
        for path in sorted(log_files):
            with open(path) as f:
                all_text += f.read() + "\n"

        print(f"  📄 Loaded {len(log_files)} log files | {len(all_text):,} characters")

        # Tokenise the entire corpus at once, then chunk into blocks
        tokens = tokenizer(
            all_text,
            return_tensors="pt",
            add_special_tokens=True
        )["input_ids"].squeeze(0)

        print(f"  🔢 Tokenised → {len(tokens):,} tokens")

        # Chunk into max_length blocks (drop last partial chunk)
        for start in range(0, len(tokens) - max_length, max_length):
            chunk = tokens[start : start + max_length]
            self.examples.append(chunk)

        print(f"  📦 Created {len(self.examples)} training chunks of {max_length} tokens")

    def __len__(self):
        return len(self.examples)

    def __getitem__(self, idx):
        return self.examples[idx]


# ─────────────────────────────────────────────────────────────────────────────
# 2. Training Loop (Sir's exact 5 steps)
# ─────────────────────────────────────────────────────────────────────────────

def train(args):
    device = torch.device(args.device)
    print(f"\n{'═' * 60}")
    print(f"  CustomMiniDeepSeek — Training")
    print(f"  Device: {device} | Epochs: {args.epochs} | LR: {args.lr}")
    print(f"{'═' * 60}\n")

    # ── Tokenizer ──────────────────────────────────────────────────────────
    print("📚 Loading tokenizer (GPT-2)…")
    tokenizer = AutoTokenizer.from_pretrained("gpt2")
    tokenizer.pad_token = tokenizer.eos_token

    # ── Dataset ────────────────────────────────────────────────────────────
    print("\n📂 Building dataset from log files…")
    dataset    = LogDataset(tokenizer, max_length=args.seq_len)
    dataloader = DataLoader(dataset, batch_size=args.batch_size, shuffle=True)

    if len(dataset) == 0:
        print("❌ No training examples. Generate logs first.")
        return

    # ── Model ──────────────────────────────────────────────────────────────
    config = MiniDeepSeekConfig(
        window_size  = args.window_size,
        num_hidden_layers = args.num_layers,
    )
    model = CustomMiniDeepSeek(config).to(device)

    print(f"\n🏗  Model built:")
    print(f"    Parameters   : {model.num_parameters():,}")
    print(f"    Memory (fp32): {model.memory_estimate_mb():.1f} MB")
    print(f"    Window size  : {config.window_size} tokens")

    # ── Optimizer ──────────────────────────────────────────────────────────
    optimizer = optim.AdamW(model.parameters(), lr=args.lr, weight_decay=0.01)

    # Optional: cosine LR decay
    scheduler = optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=args.epochs * len(dataloader)
    )

    # ── Training loop ──────────────────────────────────────────────────────
    model.train()
    print(f"\n🚀 Starting training for {args.epochs} epoch(s)…\n")

    for epoch in range(args.epochs):
        epoch_loss = 0.0
        t0 = time.time()

        for step, batch in enumerate(dataloader):
            input_ids = batch.to(device)               # [B, T]

            # ── Step 1: Forward pass ────────────────────────────────────
            logits, loss = model(input_ids, labels=input_ids)

            # ── Step 2: Calculate loss ──────────────────────────────────
            # (already computed above inside model.forward())

            # ── Step 3: Zero gradients ──────────────────────────────────
            optimizer.zero_grad()

            # ── Step 4: Backward pass ───────────────────────────────────
            loss.backward()

            # Gradient clipping (prevents exploding gradients in LMs)
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

            # ── Step 5: Update model weights ────────────────────────────
            optimizer.step()
            scheduler.step()

            epoch_loss += loss.item()

            if (step + 1) % 5 == 0 or step == 0:
                print(f"  Epoch {epoch+1}/{args.epochs} | "
                      f"Step {step+1}/{len(dataloader)} | "
                      f"Loss: {loss.item():.4f} | "
                      f"LR: {scheduler.get_last_lr()[0]:.2e}")

        avg = epoch_loss / len(dataloader)
        elapsed = time.time() - t0
        print(f"\n  ✅ Epoch {epoch+1} done | Avg Loss: {avg:.4f} | Time: {elapsed:.1f}s\n")

    # ── Save ───────────────────────────────────────────────────────────────
    save_model(model, config, tokenizer, args.output_dir)


# ─────────────────────────────────────────────────────────────────────────────
# 3. Save (Step 4 of Sir's roadmap)
# ─────────────────────────────────────────────────────────────────────────────

def save_model(model, config, tokenizer, output_dir: str):
    os.makedirs(output_dir, exist_ok=True)
    print(f"\n{'─' * 60}")
    print(f"  💾 Saving model to {output_dir}/")

    # Save weights — try safetensors first, fall back to .pt
    try:
        from safetensors.torch import save_model as safetensors_save_model
        weights_path = os.path.join(output_dir, "model.safetensors")
        # save_model handles tied weights (embed_tokens.weight == lm_head.weight) correctly
        safetensors_save_model(model, weights_path)
        print(f"  ✅ Weights saved → model.safetensors (vLLM native format)")
    except ImportError:
        weights_path = os.path.join(output_dir, "pytorch_model.bin")
        torch.save(model.state_dict(), weights_path)
        print(f"  ⚠  safetensors not installed → saved as pytorch_model.bin")
        print(f"     Install with: pip3 install safetensors")

    # Save config.json
    config_path = os.path.join(output_dir, "config.json")
    import json
    with open(config_path, "w") as f:
        json.dump(config.to_dict(), f, indent=2)
    print(f"  ✅ Config saved  → config.json")

    # Save tokenizer
    tokenizer.save_pretrained(output_dir)
    print(f"  ✅ Tokenizer saved → tokenizer.json, vocab.json, etc.")

    print(f"\n  Files in {output_dir}/:")
    for fn in sorted(os.listdir(output_dir)):
        size = os.path.getsize(os.path.join(output_dir, fn))
        print(f"    {fn:<35} {size/1024:.1f} KB")

    print(f"\n  Next step → python3 save_and_upload.py")
    print(f"{'─' * 60}\n")


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train CustomMiniDeepSeek on log files")
    parser.add_argument("--epochs",      type=int,   default=3,                       help="Training epochs")
    parser.add_argument("--batch-size",  type=int,   default=4,                       help="Batch size")
    parser.add_argument("--seq-len",     type=int,   default=128,                     help="Sequence length (tokens)")
    parser.add_argument("--lr",          type=float, default=5e-4,                    help="Learning rate")
    parser.add_argument("--window-size", type=int,   default=128,                     help="Attention window size")
    parser.add_argument("--num-layers",  type=int,   default=4,                       help="Number of decoder layers")
    parser.add_argument("--device",      type=str,   default="cpu",                   help="cpu / cuda / mps")
    parser.add_argument("--output-dir",  type=str,   default="./my_custom_mini_deepseek", help="Save directory")
    args = parser.parse_args()

    train(args)
